txt=['themethodusedforthepreparationandreadingofcodemessagesissim', ...
     'pleintheextremeandatthesametimeimpossibleoftranslationunles', ...
     'sthekeyisknowntheeasewithwhichthekeymaybechangedisanotherpo', ...
     'intinfavoroftheadoptionofthiscodebythosedesiringtotransmiti', ...
     'mportantmessageswithouttheslightestdangeroftheirmessagesbei', ...
     'ngreadbypoliticalorbusinessrivalsetc'];